version: "3.6"

services:
  chirpstack-network-server:
    image: chirpstack/chirpstack-network-server:3
    depends_on:
      - postgresql
      - redis
      - mosquitto
      - chirpstack-gateway-bridge
    ports:
        - 8000:8000
    volumes:
      - ./configuration/chirpstack-network-server:/etc/chirpstack-network-server

  chirpstack-gateway-bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1700:1700/udp
    volumes:
      - ./configuration/chirpstack-gateway-bridge:/etc/chirpstack-gateway-bridge

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    tmpfs: /var/lib/postgresql/data:size=1G
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883

volumes:
  redisdata:
