version: "3.6"

services:

  ns_eu868:
    image: chirpstack/chirpstack-network-server:3
    depends_on:
        - postgresql
    ports:
        - 9000:8000
    volumes:
      - ./configuration/ns_eu868:/etc/chirpstack-network-server

  ns_us915:
    image: chirpstack/chirpstack-network-server:3
    depends_on:
        - postgresql
    ports:
        - 9001:8000
    volumes:
      - ./configuration/ns_us915:/etc/chirpstack-network-server

  ns_au915:
    image: chirpstack/chirpstack-network-server:3
    depends_on:
        - postgresql
    ports:
        - 9002:8000
    volumes:
      - ./configuration/ns_au915:/etc/chirpstack-network-server

  bridge:
    image: chirpstack/chirpstack-gateway-bridge:3
    ports:
      - 1800:1700/udp
    volumes:
      - ./configuration/bridge:/etc/chirpstack-gateway-bridge

  postgresql:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=root
    tmpfs: /var/lib/postgresql/data:size=1G
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883

volumes:
  redisdata:
